import { JobDepartmentArray } from './useFetchJobs'

// Only for dev purposes - prevents making multiple requests to the API while developing.
export const jobsPerDepartmentDummyData: JobDepartmentArray = [
  {
    id: 87842,
    name: 'App',
    parent_id: 43806,
    child_ids: [87847, 87852, 87850, 87848, 45530, 87849],
    jobs: [],
  },
  {
    id: 54504,
    name: 'Brand Design Studio',
    parent_id: null,
    child_ids: [],
    jobs: [],
  },
  {
    id: 45532,
    name: 'Business Development',
    parent_id: null,
    child_ids: [],
    jobs: [],
  },
  {
    id: 87841,
    name: 'Codex',
    parent_id: 43806,
    child_ids: [],
    jobs: [
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=5329400',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2662332,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 5329400,
        updated_at: '2023-10-13T09:40:03-04:00',
        requisition_id: 'Cod-6',
        title: 'Technical Business Development Lead [Codex]',
      },
    ],
  },
  {
    id: 84549,
    name: 'Communications',
    parent_id: null,
    child_ids: [],
    jobs: [
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=5276254',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2645076,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 5276254,
        updated_at: '2023-10-19T03:08:59-04:00',
        requisition_id: 'PROV-Com-16',
        title: 'Motion Designer',
      },
    ],
  },
  {
    id: 45531,
    name: 'Design',
    parent_id: null,
    child_ids: [],
    jobs: [],
  },
  {
    id: 87847,
    name: 'Desktop',
    parent_id: 87842,
    child_ids: [],
    jobs: [],
  },
  {
    id: 87852,
    name: 'Documentation',
    parent_id: 87842,
    child_ids: [],
    jobs: [],
  },
  {
    id: 45547,
    name: 'Engineering ',
    parent_id: null,
    child_ids: [],
    jobs: [
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=5419957',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2693761,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 5419957,
        updated_at: '2023-10-24T07:30:00-04:00',
        requisition_id: 'APP-QA-2',
        title: 'Desktop QA Engineer ',
      },
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=3694379',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2055210,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 3694379,
        updated_at: '2023-10-24T16:23:12-04:00',
        requisition_id: 'BACK-1050',
        title: 'Senior C++ Qt/QML developer for blockchain app',
      },
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=3702173',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2058858,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 3702173,
        updated_at: '2023-10-24T16:21:54-04:00',
        requisition_id: '93',
        title: 'Senior Mobile ClojureScript UI Developer ',
      },
    ],
  },
  {
    id: 49925,
    name: 'Finance',
    parent_id: 87845,
    child_ids: [],
    jobs: [],
  },
  {
    id: 87854,
    name: 'Infrastructure',
    parent_id: 43806,
    child_ids: [],
    jobs: [],
  },
  {
    id: 87853,
    name: 'Insights',
    parent_id: 87845,
    child_ids: [],
    jobs: [],
  },
  {
    id: 87850,
    name: 'Keycard',
    parent_id: 87842,
    child_ids: [],
    jobs: [],
  },
  {
    id: 145838,
    name: 'Leadership',
    parent_id: null,
    child_ids: [],
    jobs: [
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=5447463',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2704948,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 5447463,
        updated_at: '2023-10-24T09:07:22-04:00',
        requisition_id: 'LEAD-1',
        title: 'Chief of Staff [whole ecosystem]',
      },
    ],
  },
  {
    id: 74156,
    name: 'Legal',
    parent_id: 87845,
    child_ids: [],
    jobs: [],
  },
  {
    id: 91698,
    name: 'Logos',
    parent_id: null,
    child_ids: [],
    jobs: [],
  },
  {
    id: 43807,
    name: 'Marketing',
    parent_id: null,
    child_ids: [],
    jobs: [],
  },
  {
    id: 87848,
    name: 'Mobile',
    parent_id: 87842,
    child_ids: [],
    jobs: [],
  },
  {
    id: 87843,
    name: 'Nimbus',
    parent_id: 43806,
    child_ids: [],
    jobs: [
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=5370820',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2679527,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 5370820,
        updated_at: '2023-10-19T03:05:07-04:00',
        requisition_id: 'LIDO-1',
        title: 'Senior DevOps Engineer (Blockchain)',
      },
    ],
  },
  {
    id: 144866,
    name: 'Nomos',
    parent_id: 43806,
    child_ids: [],
    jobs: [
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=5433423',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2315608,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 5433423,
        updated_at: '2023-10-12T11:20:52-04:00',
        requisition_id: 'PROV-Nom-5',
        title: 'Applied Network Researcher',
      },
    ],
  },
  {
    id: 45548,
    name: 'People Operations',
    parent_id: 87845,
    child_ids: [],
    jobs: [],
  },
  {
    id: 45530,
    name: 'Product Design',
    parent_id: 87842,
    child_ids: [],
    jobs: [],
  },
  {
    id: 90941,
    name: 'Program Management',
    parent_id: null,
    child_ids: [],
    jobs: [],
  },
  {
    id: 43806,
    name: 'Research & Development',
    parent_id: null,
    child_ids: [
      87842, 87841, 87854, 87843, 144866, 87846, 87981, 87847, 87852, 87850,
      87848, 45530, 87849,
    ],
    jobs: [],
  },
  {
    id: 87851,
    name: 'Security',
    parent_id: 87845,
    child_ids: [],
    jobs: [],
  },
  {
    id: 87845,
    name: 'Services',
    parent_id: null,
    child_ids: [49925, 87853, 74156, 45548, 87851],
    jobs: [],
  },
  {
    id: 91697,
    name: 'Status App ',
    parent_id: null,
    child_ids: [],
    jobs: [],
  },
  {
    id: 54783,
    name: 'Technical Writing ',
    parent_id: null,
    child_ids: [],
    jobs: [],
  },
  {
    id: 87846,
    name: 'Vac',
    parent_id: 43806,
    child_ids: [],
    jobs: [
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=4460860',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2331302,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 4460860,
        updated_at: '2023-10-04T05:13:53-04:00',
        requisition_id: 'PROV-zkV-1',
        title: 'Zero Knowledge Research Engineer ',
      },
    ],
  },
  {
    id: 87981,
    name: 'Waku',
    parent_id: 43806,
    child_ids: [],
    jobs: [
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=5456032',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2707470,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 5456032,
        updated_at: '2023-10-23T11:40:19-04:00',
        requisition_id: 'WAK-GL-1',
        title: 'Growth Lead',
      },
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=3693623',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2055187,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 3693623,
        updated_at: '2023-10-04T05:13:53-04:00',
        requisition_id: 'PROV-Sec-2',
        title: 'Protocol Engineer',
      },
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=3157908',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 1830496,
        location: {
          name: 'Remote, Worldwide',
        },
        metadata: null,
        id: 3157908,
        updated_at: '2023-10-04T05:13:53-04:00',
        requisition_id: 'PROV-Sec-3',
        title: 'Protocol Researcher (Distributed Systems)',
      },
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=5175038',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2584916,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 5175038,
        updated_at: '2023-10-09T05:53:53-04:00',
        requisition_id: 'SDK-2',
        title: 'Software Engineer (Chat SDK)',
      },
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=5310503',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2656108,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 5310503,
        updated_at: '2023-10-19T03:12:53-04:00',
        requisition_id: 'PROV-Wak-13',
        title: 'Software Engineer Distributed Systems Testing',
      },
      {
        absolute_url: 'https://jobs.status.im/?gh_jid=5423094',
        data_compliance: [
          {
            type: 'gdpr',
            requires_consent: false,
            requires_processing_consent: false,
            requires_retention_consent: false,
            retention_period: null,
          },
        ],
        internal_job_id: 2694724,
        location: {
          name: 'Remote (Worldwide)',
        },
        metadata: null,
        id: 5423094,
        updated_at: '2023-10-24T12:39:05-04:00',
        requisition_id: 'WAK-BD-1',
        title: 'Technical Business Development Lead ',
      },
    ],
  },
  {
    id: 87849,
    name: 'Web',
    parent_id: 87842,
    child_ids: [],
    jobs: [],
  },
  {
    id: 0,
    name: 'No Department',
    parent_id: null,
    child_ids: [],
    jobs: [],
  },
]
